### PR TITLE
Add support for Wagtail 4.0

### PR DESCRIPTION
**Pull request by crgwbr**
Wagtail 3 and 4 rewrote a lot of how the admin chooser panels work. This adds support for those changes.

### CODE REVIEW

**Comment by seb-b** [comment]
This is great. Don't suppose this has been tested with Wagtail 3? I don't mind skipping a version so much, but it'd be useful if we could set the min version to 3+

I'll hopefully have some time  this week to have a look over this and merge it

**Comment by crgwbr** [comment]
Sorry, no, this doesn't work w/ Wagtail 3. I can submit a (much smaller) MR to add support for v3 if you want to merge and release that first, before this gets merged and released.

**Comment by seb-b** [comment]
> Sorry, no, this doesn't work w/ Wagtail 3. I can submit a (much smaller) MR to add support for v3 if you want to merge and release that first, before this gets merged and released.

No, that's fine. If there's a demand for it we can handle it then, 4+ is ok for now

**Comment by seb-b** [comment]
merged with some other changes in #97

**Pull request closed without merging**
